name: Checkout Action
on: [push]
jobs:
    checkout-action:
        runs-on: ubuntu-latest
        steps:
            - name: List before checkout
              run: ls -la
            
            - name: Checkout all files
              uses: actions/checkout@v3
            
            - name: List after checkout
              run: ls -la