name: Event Activity Type
on:
    push:
    pull_request:
        types: [opened, assigned, reopened]
    issues:
        types: [opened, closed]
    
jobs:
    checkout-latest:
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo $GITHUB_REF
                echo $GITHUB_SHA
            - uses: actions/checkout@v3