name: Run workflow based on another workflow
on: [push]
jobs:
    base-workflow:
        runs-on: ubuntu-latest
        steps:
            - name: Echo
              run: |
                echo $GITHUB_REF
                echo $GITHUB_SHA
