name: Context and Expression
on: [push, pull_request, issues, workflow_dispatch]
run-name: "Context and Expression by @${{ github.actor }}, event: ${{ github.event_name }}"
jobs:
  runs-on-issues-and-pr:
    runs-on: ubuntu-latest
    # if: github.event_name == 'issues' || github.event_name == 'pull_request'
    if: contains(fromJson('["issues", "pull_request"]'), github.event_name)
    steps:
      - name: Run only if issue has a bug label
        if: contains(github.event.issue.labels.*.name, 'bug')
        run: echo ${{ join(github.event.issue.labels.*.name, ',') }}
  using-context-and-expressions:
    runs-on: ubuntu-latest
    steps:
      - name: Expression
        run: |
          echo ${{ 1 }}
          echo ${{ 'This is string' }}
          echo ${{ null }}
          echo ${{ true }}
          echo ${{ 1 > 2 }}
          echo ${{ 'string' == 'String' }}
          echo ${{ true && false }}
          echo ${{ true || (false && true) }}
        if: github.event_name == 'pull_request'
      - name: Dumps Context
        run: |
          echo '${{ toJson(github) }}'
          echo '${{ toJson(job) }}'
          echo '${{ toJson(secrets) }}'
          echo '${{ toJson(steps) }}'
          echo '${{ toJson(runner) }}'
        if: github.event_name == 'push'
