name: First workflow
on: [push]

jobs:
    test-first-workflow:
        runs-on: ubuntu-latest
        steps:
            - name: Echo string
              run: echo "Hello world"
            
            - name: Multiline Command
              run: |
                 node -v
                 npm -v
              